### ISSUE TITLE
运行创建快捷方式bat无效果

### ISSUE THREAD

**Issue by lukesyy** [wfql1024/MultiWeChatManager#1]
什么也没有生成 桌面没有图标 目录也没有文件

**Comment by study520x** [comment]
我和你一样
![QQ截图20240801023226](https://github.com/user-attachments/assets/ac67f3bd-2423-4588-931c-33ed1e4b0928)

**Comment by wfql1024** [comment]
这个原因很多，诸如中文路径、某某指令不存在等等，新版已经可以使用应用内创建桌面快捷方式了
