### ISSUE TITLE
启动后从github上拉取多开模块失败导致无法运行。开发者答：已经使用Gitee源

### ISSUE THREAD

**Issue by geelinsir** [wfql1024/MultiWeChatManager#10]
![image](https://github.com/user-attachments/assets/b67df864-ff8e-47c5-9d7a-d3fc684d320d)
如果可以的话建议内置模块或改用国内源

**Comment by wfql1024** [comment]
好，刷新也会重新尝试获取的，虽然我多次测试过没开代理情况下也能正常获取，不过下版本就弄到Gitee去吧
