### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by jiayihello** [wfql1024/MultiWeChatManager#11]
![image](https://github.com/user-attachments/assets/4adcc11b-ec7c-4c47-9b48-256f37518666)
打开后这样，无法选中账号，点击没反应
软件内创建快捷方式，点击创建出来的调试版后没有视频中的日志窗口

**Comment by wfql1024** [comment]
需要配置，参考初版发布视频：https://www.bilibili.com/video/BV13XvPe2E6i/?vd_source=80b21baae402176756ff83c5ff270e95#reply112867831449830
调试版是点击下方状态栏开启

**Comment by lffw001** [comment]
第一次使用要先点设置---应用设置，确定后点手动登录，登录一个号配置一个号才能进行后续操作
