### ISSUE TITLE
没有使用快捷方式运行显示一直载入

### ISSUE THREAD

**Issue by lenlanF** [wfql1024/MultiWeChatManager#2]
没有创建快捷方式，对应bat文件执行报错，直接点击生成的exe文件，一直显示在加载中，没有办法进入主页面，在创建的时候因为一直报错所以没有使用bat文件执行，手动执行了里面的语句，改了命令行里面图标的路径

**Comment by wfql1024** [comment]
新版已发布，尝试下新版啦~
