### ISSUE TITLE
储存路径获取失败，无法调用文件管理器手动选择路径

### ISSUE THREAD

**Issue by lenlanF** [wfql1024/MultiWeChatManager#3]
存在问题：直接使用编译好的程序，储存路径获取失败，无法调用文件管理器手动选择路径，直接卡住，后续任务栏点击这个程序无反应
建议：设置不需要点手动才能看到，现在如果获取不成功的话，必须点一次手动才能看到设置。

**Comment by wfql1024** [comment]
已修复，稍后发新的releases，问题出现在依赖间的冲突，参考：https://www.cnblogs.com/flyinghou/p/14606383.html

**Comment by wfql1024** [comment]
出问题机制已基本弄清楚，应该不会复现，关掉这个tissue了
