### ISSUE TITLE
登录时仍需要手机确认

### ISSUE THREAD

**Issue by Eyion** [wfql1024/MultiWeChatManager#4]
配置了2个号，使用一键登录时2个号都要求手机确认，虽然省了第2个号扫码的功夫。

**Comment by 362700** [comment]
附议，啥原因呀！

**Comment by Eyion** [comment]
> > 配置了2个号，使用一键登录时2个号都要求手机确认，虽然省了第2个号扫码的功夫。
> 
> 首先手机应该勾选自动登录，如果是已经勾选了的，首次配置第一次登录确实还会，多重新登录一次应该就没问题了

登录时手机端只有“同步最近消息”，无自动登录的选项。

**Comment by wfql1024** [comment]
见最新关于自动登录问题的说明，本issue关闭
