### ISSUE TITLE
在对一个账号"重新配置"后，另一个已经"重新配置“过的账号自动登录失败，需要扫码登录

### ISSUE THREAD

**Issue by NightAroundDay** [wfql1024/MultiWeChatManager#5]

**Comment by NightAroundDay** [comment]
第一次打开软件
点击手动登录-扫码登录账号1-为账号1添加配置-成功配置-手动退出账号1
点击手动登录-点击切换账号-扫码登录账号2-为账号2添配置-成功配置
此时自动登录账号1失败

**Comment by NightAroundDay** [comment]
好像多开管理器要关闭重新打开然后可以自动登录成功

**Comment by wfql1024** [comment]
> 好像多开管理器要关闭重新打开然后可以自动登录成功

刚创建配置会出现这种情况，后面就可以自动登录了
