### ISSUE TITLE
不同分辨率的时候界面不随着分辨率大小变化

### ISSUE THREAD

**Issue by linhaoyuke** [wfql1024/MultiWeChatManager#7]
在不同分辨率，不同缩放时，窗口不是同比例的放大和缩小，自动登录会失效

**Comment by wfql1024** [comment]
> 在不同分辨率，不同缩放时，窗口不是同比例的放大和缩小，自动登录会失效

这个是因为之前用比例来找位置，现在改成直接点击控件了，等更新

**Comment by linhaoyuke** [comment]
> > 在不同分辨率，不同缩放时，窗口不是同比例的放大和缩小，自动登录会失效
> 
> 这个是因为之前用比例来找位置，现在改成直接点击控件了，等更新

确实是的，大概什么时候更新呢？

另外发现一个新问题，微信更新后全局更新不可用，重置后还是显示出附件中的情况
![微信截图_20240920080537](https://github.com/user-attachments/assets/6c416861-5f16-49ec-81f0-f2decb7ed18e)

**Comment by wfql1024** [comment]
> > > 在不同分辨率，不同缩放时，窗口不是同比例的放大和缩小，自动登录会失效
> > 
> > 
> > 这个是因为之前用比例来找位置，现在改成直接点击控件了，等更新
> 
> 确实是的，大概什么时候更新呢？
> 
> 另外发现一个新问题，微信更新后全局更新不可用，重置后还是显示出附件中的情况 ![微信截图_20240920080537](https://private-user-images.githubusercontent.com/156580451/369208060-6c416861-5f16-49ec-81f0-f2decb7ed18e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODQyMDQsIm5iZiI6MTcyNzA4MzkwNCwicGF0aCI6Ii8xNTY1ODA0NTEvMzY5MjA4MDYwLTZjNDE2ODYxLTVmMTYtNDllYy04MWYwLWYyZGVjYjdlZDE4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwOTMxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmE3YjgyYzhhNWY3ZDc3NTgwZjg4OWNlODY1YjU3YWZkYjQ3OGQ1ZGQzMmQyYWVmOWE0OWIzMTgwNWNmYWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7RaX_xessCeHqGTAOxLu9MNZe2X1dxCMdCwyPdchaMQ)

已修复，并且版本适配的代码将放在云端，这样未来微信更新也不用更新软件便可以获取到新版本的适配

**Comment by wfql1024** [comment]
获取登录界面大小的逻辑完善了，应该少出现失败获取的情况了，关闭
